[features]
seeds = false
[programs.localnet]
perpetuals = "PERP9EeXeGnyEqGmxGSan4nGRAFNLwTufLJmiYsTJ8j"
[programs.devnet]
perpetuals = "PERP9EeXeGnyEqGmxGSan4nGRAFNLwTufLJmiYsTJ8j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"